# YAML configuration file for Docker Compose

# Define services
services:
  front:
    container_name: fyfront
    build:       # Build the Docker image using the Dockerfile in the current directory
      context: .
      dockerfile: front.Dockerfile
    restart: always
    ports:
      - 5050:3000  # Forward the container's port 3000 to the host machine's port 3000 for accessing the backend service
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}

  #Database service using PostgreSQL image
  database:
    image: postgres:latest  # Use the latest PostgreSQL image from Docker Hub
    container_name: fydb
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - fydb:/var/lib/postgresql/data
    ports:
      - 5432:5432  # Forward the container's port 5432 to the host machine's port 5432 for accessing PostgreSQL

    # Backend service inlude Nest and Prisma
  backend:
    container_name: fyback
    build:       # Build the Docker image using the Dockerfile in the current directory
      context: .
      dockerfile: back.Dockerfile
    restart: always
    # depends_on:
    #   - database  # Ensure that the backend service starts after the database service is up and running
    ports:
      - 4000:4000  # Forward the container's port 3000 to the host machine's port 3000 for accessing the backend service
    environment:
      - DATABASE_URL=${DATABASE_URL}
  
volumes:
  fydb:
    external: true