services:
  postgres:
    container_name: fish_container
    image: postgres:latest
    environment:
      POSTGRES_DB: 'fish'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    ports:
      - '5432:5432'
