# YAML configuration file for Docker Compose

# Define services
services:

  #Database service using PostgreSQL image
  database:
    image: postgres:latest  # Use the latest PostgreSQL image from Docker Hub
    container_name: fydb
    restart: always
    # env_file:
    #   - path: ./backend.env
    volumes:
      - fydb:/var/lib/postgresql/data
    ports:
      - 5432:5432  # Forward the container's port 5432 to the host machine's port 5432 for accessing PostgreSQL

    # Backend service inlude Nest and Prisma
  backend:
    container_name: fyback
    build:       # Build the Docker image using the Dockerfile in the current directory
      context: .
    restart: always
    # depends_on:
    #   - database  # Ensure that the backend service starts after the database service is up and running
    ports:
      - 3000:3000  # Forward the container's port 3000 to the host machine's port 3000 for accessing the backend service
    # env_file:
    #   - path: ./backend.env
    #     # Load environment variables from the .env file in the current directory
  
volumes:
  fydb:
    external: true