# YAML configuration file for Docker Compose

# Define services
services:

  #Database service using PostgreSQL image
  database:
    image: postgres:latest  # Use the latest PostgreSQL image from Docker Hub
    container_name: fydb
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - fydb:/var/lib/postgresql/data
    ports:
      - 5432:5432  # Forward the container's port 5432 to the host machine's port 5432 for accessing PostgreSQL
    networks:
      fy_network:
        ipv4_address: 172.15.0.3

    # Backend service inlude Nest and Prisma
  backend:
    container_name: fyback
    build:       # Build the Docker image using the Dockerfile in the current directory
      context: .
      dockerfile: Dockerfile
    restart: always
    # depends_on:
    #   - database  # Ensure that the backend service starts after the database service is up and running
    ports:
      - 4000:4000  # Forward the container's port 4000 to the host machine's port 4000 for accessing the backend service
    networks:
      fy_network:
        ipv4_address: 172.15.0.4
    environment:
      - DATABASE_URL=${DATABASE_URL}
  
volumes:
  fydb:
    external: true

networks:
  fy_network:
    external: true